import './globals.css'
import { Inter } from 'next/font/google'
import {Providers} from "./providers";
import Sidebar from '@/components/Sidebar';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <Providers> 
        <main className='flex h-full w-full gap-4'>
          <Sidebar/>
        {children}
        </main>
        </Providers></body>
    </html>
  )
}
