import react from 'react'
export const colleges = [
    { label: "A. P. Shah Institute of Technology - Thane", value: "ap-shah-institute", description: "Engineering College" },
    { label: "Bharati Vidyapeeth College of Engineering, Belapur, Navi Mumbai", value: "bharati-vidyapeeth-college", description: "Engineering College" },
    { label: "Datta Meghe College of Engineering, Airoli, Navi Mumbai", value: "datta-meghe-college", description: "Engineering College" },
    { label: "Don Bosco Institute of Technology, Kurla (West)", value: "don-bosco-institute", description: "Engineering College" },
    { label: "Dwarkadas J. Sanghvi College of Engineering, Vile Parle West", value: "dwarkadas-sanghvi-college", description: "Engineering College" },
    { label: "Fr. Conceicao Rodrigues College of Engineering, Bandra", value: "fr-conceicao-rodrigues-college", description: "Engineering College" },
    { label: "Fr. Conceicao Rodrigues Institute of Technology, Vashi", value: "fr-conceicao-rodrigues-institute", description: "Engineering College" },
    { label: "Institute of Chemical Technology, Matunga (Autonomous)", value: "institute-of-chemical-technology", description: "Engineering College" },
    { label: "Indian Institute of Technology Bombay, Powai", value: "iit-bombay", description: "Engineering College" },
    { label: "KC College of Engineering, Thane East", value: "kc-college", description: "Engineering College" },
    { label: "K.J. Somaiya College of Engineering, Vidyavihar", value: "kj-somaiya-college", description: "Engineering College" },
    { label: "K.J. Somaiya Institute of Technology, Sion (Autonomous)", value: "kj-somaiya-institute", description: "Engineering College" },
    { label: "Konkan Gyanpeeth College of Engineering, Karjat", value: "konkan-gyanpeeth-college", description: "Engineering College" },
    { label: "Lokmanya Tilak College of Engineering, Kopar Khairane, Navi Mumbai", value: "lokmanya-tilak-college", description: "Engineering College" },
    { label: "M. H. Saboo Siddik College of Engineering - Byculla", value: "mh-saboo-siddik-college", description: "Engineering College" },
    { label: "Mahatma Gandhi Mission's College of Engineering and Technology, Kamothe", value: "mahatma-gandhi-mission-college", description: "Engineering College" },
    { label: "NMIMS Narsee Monjee Institute of Management Studies, Juhu", value: "nmims-narsee-monjee-institute", description: "Engineering College" },
    { label: "Padmabhushan Vasantdada Patil Pratishthan's College of Engineering, Sion", value: "vasantdada-patil-college", description: "Engineering College" },
    { label: "Pillai College of Engineering (Autonomous), Panvel", value: "pillai-college", description: "Engineering College" },
    { label: "Rajiv Gandhi Institute of Technology, Mumbai", value: "rajiv-gandhi-institute", description: "Engineering College" },
    { label: "Ramrao Adik Institute of Technology, Nerul", value: "ramrao-adik-institute", description: "Engineering College" },
    { label: "Rizvi College of Engineering, Bandra (West)", value: "rizvi-college", description: "Engineering College" },
    { label: "Rustomjee Academy for Global Careers, Thane", value: "rustomjee-academy", description: "Engineering College" },
    { label: "Shree L. R. Tiwari College of Engineering - Mira Bhayandar", value: "lr-tiwari-college", description: "Engineering College" },
    { label: "Saraswati College of Engineering - New Mumbai", value: "saraswati-college", description: "Engineering College" },
    { label: "Sardar Patel College of Engineering - Andheri (West)", value: "sardar-patel-college", description: "Engineering College" },
    { label: "Sardar Patel Institute of Technology - Andheri (West)", value: "sardar-patel-institute", description: "Engineering College" },
    { label: "Shah and Anchor Kutchhi Engineering College, Chembur", value: "shah-and-anchor-engineering-college", description: "Engineering College" },
    { label: "Shivajirao S. Jondhale College of Engineering, Dombivali", value: "shivajirao-jondhale-college", description: "Engineering College" },
    { label: "Sindhudurg Shikshan Prasarak Mandal's College of Engineering, Kankavli", value: "sindhudurg-college", description: "Engineering College" },
    { label: "SIES Graduate School of Technology, Nerul", value: "sies-graduate-school", description: "Engineering College" },
    { label: "SMT. Indira Gandhi College of Engineering - Ghansoli", value: "indira-gandhi-college", description: "Engineering College" },
    { label: "St. Francis Institute of Technology, Borivali", value: "st-francis-institute", description: "Engineering College" },
    { label: "Terna Engineering College, Nerul, Navi Mumbai", value: "terna-engineering-college", description: "Engineering College" },
    { label: "Thakur College of Engineering and Technology, Thakur Village, Kandivali", value: "thakur-college", description: "Engineering College" },
    { label: "Thadomal Shahani Engineering College Mumbai, Bandra (W)", value: "thadomal-shahani-engineering-college", description: "Engineering College" },
    { label: "Vidyalankar Institute of Technology, Wadala(E),Mumbai", value: "vidyalankar-institute", description: "Engineering College" },
    { label: "Vidyavardhini College of Engineering and Technology, Vasai Road(W)", value: "vidyavardhini-college", description: "Engineering College" },
    { label: "Universal Ai University, Karjat, Mumbai", value: "universal-ai-university", description: "Engineering College" },
    { label: "Usha Mittal Institute of Technology, Santacruz(W), Mumbai", value: "usha-mittal-institute", description: "Engineering College" },
    { label: "Veermata Jijabai Technological Institute, Matunga, Mumbai (Autonomous)", value: "veermata-jijabai-technological-institute", description: "Engineering College" },
    { label: "Vivekanand Education Society's Institute of Technology Mumbai, Chembur(E)", value: "vivekanand-education-society-institute", description: "Engineering College" },
    { label: "Watumull Institute of Electronics Engineering and Computer Technology, Ulhasnagar", value: "watumull-institute", description: "Engineering College" },
    { label: "Xavier Institute of Engineering Mahim (West)", value: "xavier-institute", description: "Engineering College" },
    { label: "Yadavrao Tasgaonkar Institute of Engineering & Technology (YTIET), Bhivpuri", value: "yadavrao-tasgaonkar-institute", description: "Engineering College" },
    { label: "Hotel management", value: "hotel-management", description: "Hotel Management College" }
  ];